Markdown:
  WarnInvalid: true
  Autodetect: true

# Keep in sync with MARKDOWN_EXTENSIONS
Layout/CommentIndentation: &markdown_excludes
  Exclude:
    - '**/*.md'
    - '**/*.livemd'
    - '**/*.markdown'
    - '**/*.mdown'
    - '**/*.mdwn'
    - '**/*.mdx'
    - '**/*.mkd'
    - '**/*.mkdn'
    - '**/*.mkdown'
    - '**/*.ronn'
    - '**/*.scd'
    - '**/*.workbook'

Layout/LeadingCommentSpace:
  <<: *markdown_excludes

Layout/TrailingBlankLines:
  <<: *markdown_excludes

Layout/TrailingEmptyLines:
  <<: *markdown_excludes

Layout/EmptyLineBetweenDefs:
  <<: *markdown_excludes

Lint/DuplicateRequire:
  <<: *markdown_excludes

Lint/DuplicateMethods:
  <<: *markdown_excludes

Lint/RedundantCopDisableDirective:
  <<: *markdown_excludes

Lint/RedundantCopEnableDirective:
  <<: *markdown_excludes

Lint/RedundantRequireStatement:
  <<: *markdown_excludes

Lint/UnusedMethodArgument:
  <<: *markdown_excludes

Lint/UnusedBlockArgument:
  <<: *markdown_excludes

Lint/UselessAssignment:
  <<: *markdown_excludes

Lint/UselessMethodDefinition:
  <<: *markdown_excludes

Lint/UselessAccessModifier:
  <<: *markdown_excludes

Lint/Void:
  <<: *markdown_excludes

Naming/FileName:
  <<: *markdown_excludes

Style/AsciiComments:
  <<: *markdown_excludes

Style/Documentation:
  <<: *markdown_excludes

Style/CommentAnnotation:
  <<: *markdown_excludes

Style/FrozenStringLiteralComment:
  <<: *markdown_excludes

Layout/LineLength:
  IgnoredPatterns:
    - !ruby/regexp /^\#/
